### ISSUE TITLE
Read my own music from cloud

### ISSUE THREAD

**Issue by shuaibidshuaib** [iamAbhishekkumar/Luna#19]
Pls sir help me im kind of newbie to flutter, i want the app to display my own music from cloud instead of yours pls how can i do that, i saw that u use firebase , pls assist me . I  working on a school project and i need to submit it .

**Comment by iamAbhishekkumar** [comment]
Your own music? If you mean, the songs which are locally present. Then [this](https://pub.dev/packages/audioplayers/example) would be helpful, since just_audio is itself using audio players, so you can try to load your file as follows : 
```
Future _loadFile() async {
    final bytes = await readBytes(Uri.parse(kUrl1));
    final dir = await getApplicationDocumentsDirectory();
    final file = File('${dir.path}/audio.mp3');

    await file.writeAsBytes(bytes);
    if (file.existsSync()) {
      setState(() => localFilePath = file.path);
    }
  }
```

**Comment by shuaibidshuaib** [comment]
Hello brother i tried running my telegram but were having network  issues
in my area (im from africa), well please can you help me on how to store my
own music in the firebase and make them appear in the luna app , just like
how yours did, ill love to get response thank you sir. pls help me , im a
newbie to flutter and im trying to learn something from your project to
apply it in my school project.

**Comment by shuaibidshuaib** [comment]
Like i mean even if its similar to this
https://raw.githubusercontent.com/salvadordeveloper/TikTok-Flutter/master/images/database.png
