### ISSUE TITLE
Your own music? If you mean, the songs which are locally present. Then [this](https://pub.dev/packages/audioplayers/example) would be helpful, since just_audio is itself using audio players, so you can try to load your file as follows :

### ISSUE THREAD

**Issue by shuaibidshuaib** [iamAbhishekkumar/Luna#20]
Thanks sir , but what i really meant was a way to make the app read my own music from cloud  just like how yours did, pls take a look at this https://github.com/TheAlphamerc/flutter_twitter_clone/wiki   , like i want you to help me with the similar way of setup.

**Comment by shuaibidshuaib** [comment]
![C1lun](https://user-images.githubusercontent.com/87182339/135768472-1048af31-14b4-4234-b2c1-8a3b67d83102.JPG)
![2luna](https://user-images.githubusercontent.com/87182339/135768503-fe1c46ff-5ae5-4f48-abf3-35e1b7d1484b.JPG)
![3luna](https://user-images.githubusercontent.com/87182339/135768512-b69e8432-ee66-4be7-9a55-0666b3e5bb58.JPG)

Please sir view this pics to view the errors im encountering, i run flutter build apk --release, it failed & im using flutter 2.0.5

**Comment by iamAbhishekkumar** [comment]
Brother, This kind of error is generally due to your flutter, try to update your SDK, in my pubspec.yaml, min requirement is :    sdk: ">=2.12.0 <3.0.0".

**Comment by shuaibidshuaib** [comment]
OK brother thanks
